import { describe, expect, it } from "vitest";
import {
  cbsaTableStats,
  getMetro,
  lookupCbsaForZip,
  resolveMetroQuery,
  searchMetros,
} from "@/lib/geo/cbsa-lookup";
import { lookupZip } from "@/lib/geo/zip-lookup";

/**
 * The ZIP → metro area table, and the three ways it is read.
 *
 * The table itself is generated by `scripts/build-cbsa-table.ts` from Census and
 * OMB files. These tests are not re-deriving that join; they are pinning the
 * handful of answers a wrong regeneration would silently change — a truncated
 * file, a stale delineation vintage, a `city, state` column read as `state,
 * city` — plus the whole of the matching behaviour, which is ours.
 */

const HOUSTON = "26420";

describe("the bundled table", () => {
  it("holds the whole country, not a truncated file", () => {
    // A partial write is otherwise invisible: whatever survived keeps resolving
    // and everyone else quietly stops being in a metro. The ZIP count is well
    // below `zipCount()` on purpose — about a quarter of US ZIPs belong to no
    // CBSA at all, which is rural America and not a gap.
    const stats = cbsaTableStats();
    expect(stats.metros).toBeGreaterThan(900);
    expect(stats.zips).toBeGreaterThan(28_000);
  });

  it("was built from a delineation vintage the code knows about", () => {
    // The titles move between vintages ("West Palm Beach" → "Pompano Beach" →
    // back again), so a listing published under one and searched under another
    // is a real mismatch. Pinning the stamp makes a regeneration a deliberate
    // act with a backfill attached — see the script.
    expect(cbsaTableStats().vintage).toBe("2023-07");
  });

  it("carries the CURRENT title, not a retired one", () => {
    // 2023 renamed this metro from "Houston-The Woodlands-Sugar Land". A table
    // built from an older delineation would still resolve every ZIP correctly
    // and label them all with a name OMB no longer uses, which is exactly the
    // kind of staleness no other assertion here would catch.
    expect(getMetro(HOUSTON)?.title).toBe("Houston-Pasadena-The Woodlands, TX");
  });
});

describe("lookupCbsaForZip", () => {
  it("puts a downtown ZIP and a suburb thirty miles out in the SAME metro", () => {
    // This is the entire reason the feature exists. A city-name filter puts
    // Katy in "Katy" and Sugar Land in "Sugar Land", so an employer searching
    // Houston misses both — and they are a short drive from the middle of it. A
    // CBSA is county-based, so all three come back together.
    for (const zip of ["77002", "77494", "77478"]) {
      expect(lookupCbsaForZip(zip)?.code, zip).toBe(HOUSTON);
    }
  });

  it("resolves Puerto Rico, which has its own metros", () => {
    // Squarely in this product's audience, and easy to lose: PR arrives from a
    // separate GeoNames file and separate OMB rows.
    expect(lookupCbsaForZip("00901")?.title).toBe("San Juan-Bayamón-Caguas, PR");
  });

  it("returns null for a rural ZIP rather than the nearest metro", () => {
    // OMB deliberately leaves rural counties outside every CBSA. Snapping them
    // to the closest one would put somebody in a labour market they cannot
    // reach, which is worse for both sides than being absent from that filter.
    const rural = lookupCbsaForZip("59012");
    expect(rural).toBeNull();
    // And they are still a real ZIP with real coordinates, so the radius search
    // — the control that exists for exactly these people — still finds them.
    expect(lookupZip("59012")).not.toBeNull();
  });

  it("takes the leading five digits and rejects anything shorter", () => {
    expect(lookupCbsaForZip("77002-1234")?.code).toBe(HOUSTON);
    expect(lookupCbsaForZip(" 77002 ")?.code).toBe(HOUSTON);
    expect(lookupCbsaForZip("770")).toBeNull();
    expect(lookupCbsaForZip("")).toBeNull();
    expect(lookupCbsaForZip(null)).toBeNull();
  });

  it("returns null for five digits that are not a US ZIP", () => {
    // A Mexican código postal, most often. Those people keep whatever they
    // typed on their résumé and are simply not on the map.
    expect(lookupCbsaForZip("99999")).toBeNull();
  });
});

describe("searchMetros", () => {
  it("finds a metro by its first city", () => {
    expect(searchMetros("houston")[0]?.code).toBe(HOUSTON);
  });

  it("finds one by a SECONDARY city in its title", () => {
    // A CBSA title names the towns people actually live in, and somebody in
    // Conroe calls home "The Woodlands", not "Houston". Matching any token of
    // the title is what makes the box usable by the person typing it.
    expect(searchMetros("woodlands")[0]?.code).toBe(HOUSTON);
  });

  it("ANDs the tokens, in any order", () => {
    // `hous tx` narrows; it does not fall back to everything matching `hous`.
    expect(searchMetros("hous tx").map((m) => m.code)).toEqual([HOUSTON]);
    expect(searchMetros("tx hous").map((m) => m.code)).toEqual([HOUSTON]);
  });

  it("ignores accents and case in both directions", () => {
    // The audience types Spanish on phone keyboards where the accented vowel is
    // a long-press away. `San Juan-Bayamón` has to be reachable as `bayamon`,
    // and an accented query has to reach an unaccented title.
    expect(searchMetros("bayamon")[0]?.title).toContain("Bayamón");
    expect(searchMetros("BAYAMÓN")[0]?.title).toContain("Bayamón");
  });

  it("puts the metropolitan area ahead of the micropolitan one of the same name", () => {
    // Miami, Florida and Miami, Oklahoma are both real. Showing the small one
    // first would read as a bug to every employer who has heard of the other.
    const [first, second] = searchMetros("miami");
    expect(first?.title).toContain("Fort Lauderdale");
    expect(second?.title).toBe("Miami, OK");
  });

  it("prefers a title the query STARTS to spell", () => {
    // `angeles` matches Los Angeles and Port Angeles, WA. The first is where
    // the query begins the title.
    expect(searchMetros("angeles")[0]?.title).toContain("Los Angeles");
  });

  it("matches NOBODY on a query with no token of two characters", () => {
    // A one-letter prefix covers most of the column, so answering `a` with the
    // whole country would be a page-out dressed up as a suggestion list. Same
    // floor, same reasoning, as `nameSearchTokens`.
    expect(searchMetros("a")).toEqual([]);
    expect(searchMetros("")).toEqual([]);
    expect(searchMetros("  ")).toEqual([]);
  });

  it("caps the list", () => {
    // `tx` matches every Texas metro. The suggestion list is not a way to page
    // out the reference table either.
    expect(searchMetros("tx").length).toBeLessThanOrEqual(8);
    expect(searchMetros("tx", 3)).toHaveLength(3);
  });
});

describe("resolveMetroQuery", () => {
  it("accepts a CBSA code — what the autocomplete and a shared URL carry", () => {
    const result = resolveMetroQuery("26420");
    expect(result.status).toBe("exact");
    expect(result.status === "exact" && result.metro.title).toContain("Houston");
  });

  it("accepts the full title, which is what the picker submits", () => {
    // `MetroPicker` writes the title into the box rather than a hidden code, so
    // that the filter keeps working with no JavaScript and the URL stays
    // readable. That only holds if a pasted title resolves exactly.
    const result = resolveMetroQuery("Houston-Pasadena-The Woodlands, TX");
    expect(result.status === "exact" && result.metro.code).toBe(HOUSTON);
  });

  it("resolves a typed city when only one metro matches", () => {
    // The no-JavaScript path, and the one an employer takes when they ignore
    // the dropdown and press Buscar.
    const result = resolveMetroQuery("houston");
    expect(result.status === "exact" && result.metro.code).toBe(HOUSTON);
  });

  it("refuses to GUESS between two metros of the same name", () => {
    // Portland, Oregon and Portland, Maine. Picking one would answer a question
    // the employer did not ask, and they would read the results as though it
    // had been their choice — so nothing is filtered and both are offered.
    const result = resolveMetroQuery("portland");
    expect(result.status).toBe("ambiguous");
    if (result.status !== "ambiguous") return;
    expect(result.typed).toBe("portland");
    expect(result.options.map((o) => o.title)).toEqual([
      "Portland-South Portland, ME",
      "Portland-Vancouver-Hillsboro, OR-WA",
    ]);
  });

  it("prefers an exact title over the metros it prefixes", () => {
    // `Springfield, IL` is a complete title AND a prefix of nothing else once
    // both tokens have to match — but the rule that matters is the general one:
    // a title typed in full wins outright rather than joining a list of
    // near-misses.
    const result = resolveMetroQuery("Springfield, MO");
    expect(result.status === "exact" && result.metro.title).toBe("Springfield, MO");
  });

  it("says so when it recognises nothing", () => {
    // Not silently unfiltered. An employer reads whatever comes back as the
    // answer to what they asked, so returning the whole country under a
    // misspelling is a wrong answer, not an empty result.
    const result = resolveMetroQuery("Guadalajara");
    expect(result.status).toBe("unknown");
    expect(result.status === "unknown" && result.typed).toBe("Guadalajara");
  });

  it("distinguishes an ABSENT filter from an unrecognised one", () => {
    // `absent` renders no message at all; `unknown` renders a correction. If
    // these collapsed, every unfiltered search would apologise for something.
    expect(resolveMetroQuery("").status).toBe("absent");
    expect(resolveMetroQuery(null).status).toBe("absent");
    expect(resolveMetroQuery("   ").status).toBe("absent");
    expect(resolveMetroQuery("a").status).toBe("unknown");
  });
});
